tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "mas"

# Shell
brew "fzf"
brew "git-delta"
brew "htop"

# Development
brew "commitizen"
brew "node"
brew "pre-commit"
brew "tldr"
cask "cyberduck"
cask "docker"
cask "drawio"
cask "google-cloud-sdk"
cask "jetbrains-toolbox"
cask "ngrok"
cask "phpstorm"
cask "pritunl"

# General
cask "appcleaner"
cask "firefox"
cask "google-chrome"
cask "iterm2"
cask "microsoft-teams"
cask "notion"
cask "spectacle"
cask "sublime-text"
mas "1Password 7", id: 1333542190
mas "Amphetamine", id: 937984704
mas "Battery Time", id: 547105832
mas "JSONPeep", id: 1458969831
mas "Sequel Ace", id: 1518036000
mas "Slack", id: 803453959
mas "The Unarchiver", id: 425424353
mas "Todoist", id: 585829637

# Personal
cask "calibre"
cask "spotify"
cask "telegram"
cask "whatsapp"
